name: medo_e_delirio_app
description: Aplicativo do podcast Medo e Delírio em Brasília

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.00+40

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_repository:
    path: packages/audio_repository
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  http: ^1.1.0
  shared_preferences: ^2.0.15
  just_audio: ^0.9.24
  path_provider: ^2.0.11
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  cloud_firestore: ^4.8.4
  provider: ^6.0.3
  share_plus: ^7.1.0
  json_annotation: ^4.8.1
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.1.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300